# Generated by Django 4.2 on 2023-04-26 07:31

import django.contrib.postgres.fields
from django.db import migrations, models
import http


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_schemas'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='ignored_properties',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), null=True, size=None),
        ),
        migrations.AddField(
            model_name='scenario',
            name='status_code',
            field=models.SmallIntegerField(default=http.HTTPStatus['OK']),
        ),
    ]
