# Generated by Django 5.0.2 on 2024-02-10 02:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_evaluation_creator"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taskrecord",
            name="message",
        ),
        migrations.AddField(
            model_name="taskrecord",
            name="messages",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="scenario",
            name="response",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="taskrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("ok", "OK"),
                    ("invalid", "Invalid"),
                    ("invalid_json", "parse error or invalid content-type"),
                    ("invalid_http_status", "invalid http status code"),
                    ("timeout", "timeout"),
                    ("mismatch", "response do not match"),
                    ("error", "4xx or 500x"),
                ],
                max_length=20,
            ),
        ),
    ]
