# Generated by Django 5.0.2 on 2024-02-10 05:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_task_record_messages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskrecord",
            name="status",
            field=models.CharField(
                choices=[("ok", "OK"), ("invalid", "Invalid"), ("timeout", "Timeout"), ("error", "4xx or 500x")],
                max_length=20,
            ),
        ),
    ]
