# Generated by Django 5.0.2 on 2024-02-25 21:44

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_taskrecord_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="image",
            field=models.CharField(
                help_text="Path to GitHub hosted docker image. Example: ghcr.io/fiit-databases/dbs-python-example:master",
                max_length=255,
                validators=[apps.core.validators.OptionalSchemeURLValidator()],
                verbose_name="Docker Image",
            ),
        ),
    ]
