# Generated by Django 5.0.3 on 2024-03-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_task_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="additional_information",
            field=models.JSONField(default=dict),
        ),
    ]
